/**
 * Blog cover gates (public/blog/<slug>-hero.svg, generated by
 * `npm run gen:heroes` from scripts/blog-cover.mjs).
 *
 * The covers' text is outlined to <path>, so nothing about a stale cover is
 * visible to grep. Three independent checks:
 *
 *   1. STAMP — every cover carries `<metadata data-title data-cap
 *      data-generator>`; the title must equal the English frontmatter title
 *      and the caption must equal the one blog-kind.ts computes today
 *      (kind, IR number, category). A retitled post, a renumbered incident or
 *      a changed category fails here with a readable diff.
 *   2. RE-RENDER — the generator is pure, so each cover is rendered again in
 *      memory and must equal the file byte for byte: the stamp cannot drift
 *      from the glyphs actually drawn.
 *   3. GEOMETRY, read back from the SVG itself (not from the generator's
 *      numbers): the title glyphs' ink boxes, computed from the outline paths
 *      in <defs>, clear the icon ring by >= 12px; every caption and title glyph
 *      is inside the safe area; the caption is >= 11px when the cover is shown
 *      370px wide (the /blog/ grid card).
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  readPosts,
  renderCover,
  captionText,
  COVER_GENERATOR,
  ICON,
  RING_EDGE,
  ICON_CLEARANCE,
  SAFE,
  assertLayout,
  fitTitle,
} from '../../scripts/blog-cover.mjs';
import { incidentNumbers } from './blog-kind';

const ROOT = process.cwd();
const PUBLIC_BLOG = join(ROOT, 'public/blog');
const posts = readPosts(ROOT);
const numbers = incidentNumbers(posts);
// The generator writes LF; a Windows checkout with core.autocrlf=true (this
// repo has no .gitattributes) turns that into CRLF on disk. Line endings are
// not staleness, so compare LF-normalised.
const coverOf = (slug: string) =>
  readFileSync(join(PUBLIC_BLOG, `${slug}-hero.svg`), 'utf8').replace(/\r\n/g, '\n');

const decode = (s: string) =>
  s.replace(/&quot;/g, '"').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&amp;/g, '&');

function stamp(svg: string): Record<string, string> {
  const m = svg.match(/<metadata\b([^>]*)\/>/);
  if (!m) return {};
  const out: Record<string, string> = {};
  for (const [, k, v] of m[1].matchAll(/\sdata-([a-z-]+)="([^"]*)"/g)) out[k] = decode(v);
  return out;
}

// ── SVG geometry read-back ────────────────────────────────────────────────────
type Box = { x1: number; y1: number; x2: number; y2: number };

/** Box of an outlined glyph from its path data (all control points: a superset of the ink). */
function pathBox(d: string): Box | null {
  const nums = [...d.matchAll(/-?\d*\.?\d+(?:e-?\d+)?/gi)].map((m) => Number(m[0]));
  if (/[^MLQCZ\d\s.\-e]/i.test(d)) throw new Error(`unexpected path command in ${d.slice(0, 40)}`);
  if (nums.length < 2) return null;
  const b = { x1: Infinity, y1: Infinity, x2: -Infinity, y2: -Infinity };
  for (let i = 0; i + 1 < nums.length; i += 2) {
    b.x1 = Math.min(b.x1, nums[i]);
    b.x2 = Math.max(b.x2, nums[i]);
    b.y1 = Math.min(b.y1, nums[i + 1]);
    b.y2 = Math.max(b.y2, nums[i + 1]);
  }
  return b;
}

/** Placed glyph boxes, and run sizes, inside `<g data-role="ROLE">`. */
function roleGlyphs(svg: string, role: string) {
  const defs = new Map<string, string>();
  for (const [, id, d] of svg.matchAll(/<path id="(g\d+)" d="([^"]*)"\/>/g)) defs.set(id, d);
  const block = svg.match(new RegExp(`<g data-role="${role}">\\n([\\s\\S]*?)\\n</g>`));
  if (!block) throw new Error(`no <g data-role="${role}">`);
  const boxes: Box[] = [];
  const scales: number[] = [];
  for (const [, tx, ty, k, inner] of block[1].matchAll(
    /<g transform="translate\(([-\d.]+) ([-\d.]+)\) scale\(([\d.e-]+)\)"[^>]*>(.*?)<\/g>/g,
  )) {
    const s = Number(k);
    scales.push(s);
    for (const [, id, ux] of inner.matchAll(/<use href="#(g\d+)"(?: x="([-\d.]+)")?\/>/g)) {
      const pb = pathBox(defs.get(id) ?? '');
      if (!pb) continue;
      const ox = Number(ux ?? 0);
      boxes.push({
        x1: Number(tx) + (ox + pb.x1) * s,
        x2: Number(tx) + (ox + pb.x2) * s,
        y1: Number(ty) + pb.y1 * s,
        y2: Number(ty) + pb.y2 * s,
      });
    }
  }
  return { boxes, scales };
}

function ringClearance(b: Box) {
  const dx = Math.max(b.x1 - ICON.cx, 0, ICON.cx - b.x2);
  const dy = Math.max(b.y1 - ICON.cy, 0, ICON.cy - b.y2);
  return Math.hypot(dx, dy) - RING_EDGE;
}

// ── 1. Stamp ──────────────────────────────────────────────────────────────────
describe('cover stamp matches the post', () => {
  for (const p of posts) {
    it(`${p.slug}: title, caption and generator`, () => {
      const s = stamp(coverOf(p.slug));
      expect(s, 'cover stamp is missing or does not match the post — run npm run gen:heroes').toMatchObject({
        generator: COVER_GENERATOR,
        slug: p.slug,
        title: p.title,
        cap: captionText(p, numbers),
      });
    });
  }
});

// ── 2. Re-render ──────────────────────────────────────────────────────────────
describe('cover on disk is the current render', () => {
  for (const p of posts) {
    it(`${p.slug}: byte-identical to a fresh render`, () => {
      expect(coverOf(p.slug) === renderCover(p, numbers).svg, 'stale cover — run npm run gen:heroes').toBe(true);
    });
  }
});

// ── 3. Geometry ───────────────────────────────────────────────────────────────
describe('cover geometry', () => {
  it('the ring the checks measure against is the ring that is drawn', () => {
    for (const p of posts) {
      expect(coverOf(p.slug)).toContain(`<circle cx="${ICON.cx}" cy="${ICON.cy}" r="${ICON.r}" `);
    }
  });

  for (const p of posts) {
    it(`${p.slug}: title clears the icon ring by >= ${ICON_CLEARANCE}px, all text in the safe area`, () => {
      const svg = coverOf(p.slug);
      const title = roleGlyphs(svg, 'title');
      const caption = roleGlyphs(svg, 'caption');
      // Vacuity guard: one box per visible title glyph was found.
      expect(title.boxes.length).toBe(p.title.replace(/\s/g, '').length);
      const worst = Math.min(...title.boxes.map(ringClearance));
      expect(worst, 'title ink vs ring edge (px)').toBeGreaterThanOrEqual(ICON_CLEARANCE);
      for (const b of [...title.boxes, ...caption.boxes]) {
        expect(b.x1).toBeGreaterThanOrEqual(SAFE.left - 0.01);
        expect(b.x2).toBeLessThanOrEqual(SAFE.right + 0.01);
        expect(b.y1).toBeGreaterThanOrEqual(SAFE.top - 0.01);
        expect(b.y2).toBeLessThanOrEqual(SAFE.bottom + 0.01);
      }
    });

    it(`${p.slug}: caption is >= 11px at a 370px-wide card`, () => {
      const { scales, boxes } = roleGlyphs(coverOf(p.slug), 'caption');
      expect(boxes.length).toBeGreaterThan(0);
      // Plex Mono is 1000 units/em, so scale × 1000 is the run's px size.
      for (const s of scales) expect((s * 1000 * 370) / 1200).toBeGreaterThanOrEqual(11);
    });
  }
});

// ── Generator assertions throw (they are the build-time half of the gate) ─────
describe('generator layout assertions', () => {
  it('throws on a glyph inside the ring clearance', () => {
    const near = { x1: ICON.cx - RING_EDGE - 5, x2: ICON.cx - RING_EDGE - 1, y1: ICON.cy - 2, y2: ICON.cy + 2, ch: 'x' };
    expect(() => assertLayout('probe', [near])).toThrow(/from the icon ring/);
  });
  it('throws on a glyph outside the safe area', () => {
    expect(() => assertLayout('probe', [{ x1: 10, x2: 20, y1: 300, y2: 320, ch: 'x' }])).toThrow(/safe area/);
  });
  it('steps the title size down rather than collide, and fails when nothing fits', () => {
    const long = 'Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua';
    expect(() => fitTitle(long)).toThrow(/does not fit/);
  });
});
