/**
 * In-article blog diagram gates (public/blog/<slug>-diagram.svg, generated by
 * `node scripts/replate-diagrams.mjs` from scripts/diagram-src/).
 *
 * The diagrams ship as <img>, so they cannot follow the theme or load a web
 * font: every label is outlined IBM Plex, and the plate is the light card in
 * both themes. These checks hold that in place:
 *
 *   1. NO LIVE TEXT — no <text>, <tspan> or font-* attribute survives. A
 *      system-font label (the pre-2026-10-02 state) fails here.
 *   2. ROOT PINNED — viewBox, width, height and role equal the manifest below,
 *      taken from main before the re-plate; aria-label equals the source's.
 *      Markdown sets no dimensions, so a changed viewBox would silently
 *      re-flow every post that embeds the diagram.
 *   3. RE-RENDER — the generator is pure; each file must equal a fresh render
 *      of its source byte for byte, so the public copy cannot be hand-edited.
 *   4. GEOMETRY — every shape (rect, line, path, circle, polyline, marker, g
 *      transform) has exactly the source's attributes except fill/stroke,
 *      which may only change through the PALETTE map.
 *   5. PALETTE — every colour is a light-theme Field Manual token.
 *   6. REFERENCES — every /blog/*-diagram.svg a post embeds exists here.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import {
  replate,
  parseXml,
  diagramFiles,
  SRC_DIR,
  OUT_DIR,
  PALETTE,
  ALLOWED_COLOURS,
  DIAGRAM_RE,
} from '../../scripts/replate-diagrams.mjs';

const ROOT = process.cwd();

// Root attributes of every diagram as they were on main at 3db8da7.
const MANIFEST: Record<string, { viewBox: string; width: string | null; height: string | null; role: string }> = {
  'common-gitlab-ci-mistakes-diagram.svg': { viewBox: '0 0 1200 660', width: null, height: null, role: 'img' },
  'convert-docker-run-to-compose-diagram.svg': { viewBox: '0 0 1200 660', width: null, height: null, role: 'img' },
  'cron-expressions-explained-diagram.svg': { viewBox: '0 0 1200 660', width: null, height: null, role: 'img' },
  'cron-to-systemd-timers-diagram.svg': { viewBox: '0 0 1200 620', width: null, height: null, role: 'img' },
  'debug-alertmanager-routing-diagram.svg': { viewBox: '0 0 1200 660', width: null, height: null, role: 'img' },
  'debug-prometheus-relabeling-diagram.svg': { viewBox: '0 0 1200 620', width: null, height: null, role: 'img' },
  'docker-run-vs-compose-diagram.svg': { viewBox: '0 0 1200 660', width: null, height: null, role: 'img' },
  'env-example-drift-diagram.svg': { viewBox: '0 0 1200 660', width: null, height: null, role: 'img' },
  'github-actions-if-condition-always-true-diagram.svg': { viewBox: '0 0 1200 640', width: null, height: null, role: 'img' },
  'github-actions-security-misconfigurations-diagram.svg': { viewBox: '0 0 1200 720', width: null, height: null, role: 'img' },
  'github-actions-workflow-not-triggering-filters-diagram.svg': { viewBox: '0 0 1200 720', width: null, height: null, role: 'img' },
  'how-alertmanager-routing-works-diagram.svg': { viewBox: '0 0 1200 680', width: null, height: null, role: 'img' },
  'kubernetes-service-has-no-endpoints-diagram.svg': { viewBox: '0 0 1200 600', width: '1200', height: null, role: 'img' },
  'learn-devops-in-90-days-diagram.svg': { viewBox: '0 0 1200 640', width: null, height: null, role: 'img' },
  'logql-vs-promql-diagram.svg': { viewBox: '0 0 1200 730', width: null, height: null, role: 'img' },
  'prometheus-relabel-configs-explained-diagram.svg': { viewBox: '0 0 1200 640', width: null, height: null, role: 'img' },
  'reading-promql-diagram.svg': { viewBox: '0 0 1200 660', width: null, height: null, role: 'img' },
  'regex-for-log-lines-diagram.svg': { viewBox: '0 0 1200 640', width: null, height: null, role: 'img' },
  'terraform-forces-replacement-diagram.svg': { viewBox: '0 0 1200 580', width: '1200', height: null, role: 'img' },
  'unable-to-get-local-issuer-certificate-diagram.svg': { viewBox: '0 0 1200 560', width: '1200', height: null, role: 'img' },
  'unifying-cve-ignore-files-diagram.svg': { viewBox: '0 0 1200 720', width: null, height: null, role: 'img' },
  'unit-testing-loki-alert-rules-diagram.svg': { viewBox: '0 0 1200 640', width: null, height: null, role: 'img' },
  'validate-gitlab-ci-yml-diagram.svg': { viewBox: '0 0 1200 620', width: null, height: null, role: 'img' },
};

const read = (dir: string, f: string) => readFileSync(join(dir, f), 'utf8');

type El = { name: string; attrs?: Record<string, string>; children?: El[]; value?: string };

function rootAttrs(svg: string) {
  const tag = /<svg\b[^>]*>/.exec(svg)?.[0] ?? '';
  const get = (a: string) => new RegExp(`\\s${a}="([^"]*)"`).exec(tag)?.[1] ?? null;
  return { viewBox: get('viewBox'), width: get('width'), height: get('height'), role: get('role'), ariaLabel: get('aria-label') };
}

/** Live-text violations in a rendered diagram (empty when clean). */
function liveText(svg: string): string[] {
  const out: string[] = [];
  if (/<text\b/.test(svg)) out.push('<text>');
  if (/<tspan\b/.test(svg)) out.push('<tspan>');
  if (/font-family/.test(svg)) out.push('font-family');
  if (/\sfont-(size|weight|style)=/.test(svg)) out.push('font-* attribute');
  return out;
}

const SHAPES = new Set(['rect', 'line', 'path', 'circle', 'polyline', 'polygon', 'ellipse', 'marker', 'svg']);

/** Every non-text shape with its attributes, colours mapped through `map`. Glyph-sheet paths are skipped. */
function shapes(svg: string, map: (hex: string) => string): string[] {
  const out: string[] = [];
  const visit = (el: El, inText: boolean) => {
    for (const c of el.children ?? []) {
      if (c.name === '#text') continue;
      const text = inText || c.name === 'text';
      const glyph = c.name === 'path' && /^gl\d+$/.test(c.attrs?.id ?? '');
      const glyphRun = c.name === 'g' && /^translate\([^)]*\) scale\(/.test(c.attrs?.transform ?? '') && !!c.children?.some((k) => k.name === 'use');
      if (!text && !glyph && !glyphRun && (SHAPES.has(c.name) || (c.name === 'g' && c.attrs?.transform))) {
        const attrs = Object.entries(c.attrs ?? {})
          .filter(([k]) => !/^(font-|letter-spacing|text-anchor)/.test(k))
          .map(([k, v]) => `${k}=${k === 'fill' || k === 'stroke' ? map(v.toLowerCase()) : v}`)
          .sort();
        out.push(`${c.name}[${attrs.join(' ')}]`);
      }
      if (!glyphRun) visit(c, text);
    }
  };
  visit(parseXml(svg) as unknown as El, false);
  return out;
}

const COLOUR_RE = /\s(?:fill|stroke)="(#[0-9a-fA-F]{3,8})"/g;
function offPalette(svg: string): string[] {
  return [...new Set([...svg.matchAll(COLOUR_RE)].map((m) => m[1].toLowerCase()))].filter((c) => !ALLOWED_COLOURS.has(c));
}

const files = diagramFiles();
const publicFiles = readdirSync(OUT_DIR).filter((f) => DIAGRAM_RE.test(f)).sort();

describe('blog diagrams: the gate can fail', () => {
  // Proofs must be able to fail: each detector is run once on a sample that
  // must trip it, so a broken regex cannot pass the real files vacuously.
  it('flags live text, font attributes and off-palette colours', () => {
    expect(liveText('<svg><text x="1">a</text></svg>')).toContain('<text>');
    expect(liveText('<svg><g font-family="x"/></svg>')).toContain('font-family');
    expect(liveText('<svg><g font-size="12"/></svg>')).toContain('font-* attribute');
    expect(offPalette('<svg><rect fill="#ffffff"/></svg>')).toEqual(['#ffffff']);
    expect(rootAttrs('<svg xmlns="x" viewBox="0 0 10 20" width="10" role="img">').viewBox).toBe('0 0 10 20');
  });
  it('flags a moved shape', () => {
    const a = '<svg viewBox="0 0 10 10"><rect x="1" y="1" width="2" height="2" fill="#ffffff"/></svg>';
    const b = '<svg viewBox="0 0 10 10"><rect x="2" y="1" width="2" height="2" fill="#fffdf9"/></svg>';
    const map = (h: string) => PALETTE[h as keyof typeof PALETTE] ?? h;
    expect(shapes(b, (h) => h)).not.toEqual(shapes(a, map));
    expect(shapes(b.replace('x="2"', 'x="1"'), (h) => h)).toEqual(shapes(a, map));
  });
});

describe('blog diagrams', () => {
  it('source, public and manifest list the same files', () => {
    expect(files).toEqual(Object.keys(MANIFEST).sort());
    expect(publicFiles).toEqual(files);
  });

  it('every diagram a post embeds exists', () => {
    const refs = new Set<string>();
    const walk = (dir: string) => {
      for (const e of readdirSync(dir, { withFileTypes: true })) {
        const p = join(dir, e.name);
        if (e.isDirectory()) walk(p);
        else if (e.name.endsWith('.md')) for (const m of readFileSync(p, 'utf8').matchAll(/\/blog\/([a-z0-9-]+-diagram\.svg)/g)) refs.add(m[1]);
      }
    };
    walk(join(ROOT, 'src/content'));
    expect(refs.size).toBeGreaterThan(0);
    for (const r of refs) expect(MANIFEST, r).toHaveProperty([r]);
  });

  for (const f of files) {
    describe(f, () => {
      const out = read(OUT_DIR, f);
      const src = read(SRC_DIR, f);

      it('has no live text or font attributes', () => {
        expect(liveText(out)).toEqual([]);
      });

      it('keeps viewBox, width, height, role and aria-label', () => {
        const a = rootAttrs(out);
        const { viewBox, width, height, role } = a;
        expect({ viewBox, width, height, role }).toEqual(MANIFEST[f]);
        expect(a.ariaLabel).toBe(rootAttrs(src).ariaLabel);
        expect(a.ariaLabel?.length).toBeGreaterThan(20);
      });

      it('is byte-identical to a fresh render of its source', () => {
        expect(replate(src, { file: f }) === out).toBe(true);
      });

      it("keeps every shape's geometry", () => {
        const map = (h: string) => PALETTE[h as keyof typeof PALETTE] ?? h;
        const want = shapes(src, map);
        expect(want.length).toBeGreaterThan(3);
        expect(shapes(out, (h) => h)).toEqual(want);
      });

      it('uses only Field Manual light-theme colours', () => {
        expect(offPalette(out)).toEqual([]);
      });
    });
  }
});
