/**
 * LLM VRAM variant pages — /llm-vram-calculator/<preset>/, one entry per PRESETS item, in
 * PRESETS order. Every number in the prose comes from estimate() at module scope and is
 * printed with the result panel's own formatter, so a page can never disagree with the
 * calculator it seeds. Hand-written text (what the model is, which quant, pitfalls) is
 * keyed by preset slug; a preset without one throws at build. Model facts as of October 2026.
 */
import { estimate } from '../../lib/llm-vram-calculator/engine';
import { PRESETS } from '../../lib/llm-vram-calculator/presets';
import { formatGiB } from '../../lib/llm-vram-calculator/render';
import type { ModelPreset, Quant, VramInput, VramResult } from '../../lib/llm-vram-calculator/types';
import type { Faq } from '../tool-faqs';
import type { ToolVariant } from './index';

export interface LlmVramVariant extends ToolVariant {
  vram: VramInput;
}

const DEFAULT_CTX = 8192;
const n = (x: number) => x.toLocaleString('en-US');

interface Facts {
  p: ModelPreset;
  ctx: number;
  q4: VramResult;
  q8: VramResult;
  fp16: VramResult;
  /** Q4_K_M at the model's maximum context. */
  max: VramResult;
  /** KV cache bytes per token, in KiB. */
  kvKiB: number;
  /** Any quant / context, same preset. */
  at: (quant: Quant, context?: number) => VramResult;
}

const g = (r: VramResult) => `${formatGiB(r.totalGiB)} GiB`;
const an = (gib: number) => (gib === 8 || gib === 80 ? 'an' : 'a');
const tier = (r: VramResult) => (r.minTierGiB ? `${an(r.minTierGiB)} ${r.minTierGiB} GiB card` : 'more than a single 80 GiB card');
const cards = (r: VramResult) => r.tiers.find((t) => t.gib === r.minTierGiB)?.cards.join(', ') ?? '';
const tierWithCards = (r: VramResult) =>
  r.minTierGiB ? `${r.minTierGiB} GiB (${cards(r)})` : 'beyond any single 80 GiB card, so it needs several GPUs or a large unified-memory machine';

function facts(p: ModelPreset): Facts {
  const ctx = Math.min(DEFAULT_CTX, p.maxContext);
  const at = (quant: Quant, context = ctx) => {
    const r = estimate({ params: p.params, quant, context, preset: p.slug });
    if (!r.valid) throw new Error(`llm-vram variant ${p.slug}: ${r.error}`);
    return r;
  };
  return {
    p,
    ctx,
    q4: at('q4_k_m'),
    q8: at('q8_0'),
    fp16: at('fp16'),
    max: at('q4_k_m', p.maxContext),
    kvKiB: (2 * p.layers * p.kvHeads * p.headDim * 2) / 1024,
    at,
  };
}

interface Hand {
  /** Short name for the <title>, when the full name would overflow 60 chars. */
  short?: string;
  about: string;
  pick: (f: Facts) => string;
  pitfall: (f: Facts) => string;
  related: string;
  faqs: (f: Facts) => Faq[];
}

const R1_NOTE =
  'The R1 distills are not DeepSeek-R1 itself, which is a 671B mixture-of-experts model; each one is an existing Qwen2.5 or Llama base fine-tuned on reasoning traces generated by R1, so its memory footprint is exactly that of its base architecture.';
const R1_THINK =
  'Reasoning models write a long chain of thought before the answer, often thousands of tokens, so budget context generously: a reply that runs out of KV cache stops mid-thought.';

const HAND: Record<string, Hand> = {
  'llama-3-2-3b': {
    about:
      'Llama 3.2 3B is the larger of Meta\'s two lightweight text models from September 2024, built for on-device assistants, summarising and tool-calling where a phone, laptop or small GPU has to carry the whole model.',
    pick: (f) =>
      `At this size quantization artefacts show up sooner than on big models, so Q8_0 at ${g(f.q8)} is the sensible default on any card with 8 GiB, and even FP16 at ${g(f.fp16)} fits ${tier(f.fp16)}. Reach for Q4_K_M only for phones and integrated graphics.`,
    pitfall: (f) =>
      `The trap is the context, not the weights: at the full ${n(f.p.maxContext)} tokens the KV cache alone is ${formatGiB(f.max.kvGiB)} GiB, several times the ${formatGiB(f.q4.weightsGiB)} GiB of Q4_K_M weights. On a Mac, Apple Silicon lets the GPU use only about three quarters of unified memory by default, so an 8 GB machine has roughly 6 GB to work with.`,
    related: 'For more capability on the same card, compare Llama 3.1 8B and Qwen2.5 7B.',
    faqs: (f) => [
      {
        q: 'Can Llama 3.2 3B run on a 4 GB GPU?',
        a: `Only at a short context. Q4_K_M weights are ${formatGiB(f.q4.weightsGiB)} GiB, and with an 8,192-token cache plus 1.5 GiB of overhead the estimate is ${g(f.q4)}, which is just over 4 GiB. Dropping to 4,096 tokens brings it to ${g(f.at('q4_k_m', 4096))}.`,
      },
      {
        q: 'How much memory does Llama 3.2 3B need for its full 128k context?',
        a: `At Q4_K_M with ${n(f.p.maxContext)} tokens the estimate is ${g(f.max)}, of which ${formatGiB(f.max.kvGiB)} GiB is KV cache, so it needs ${tier(f.max)}.`,
      },
    ],
  },
  'llama-3-1-8b': {
    about:
      'Llama 3.1 8B, released by Meta in July 2024, is the most widely fine-tuned open model of its generation and the usual baseline for a local chat or coding assistant on a single consumer GPU.',
    pick: (f) =>
      `Q4_K_M at ${g(f.q4)} is the classic 8 GiB-card choice. With 12 GiB, Q8_0 at ${g(f.q8)} is close to lossless and worth the extra memory; FP16 at ${g(f.fp16)} buys almost nothing over Q8_0 for inference and needs ${tier(f.fp16)}.`,
    pitfall: (f) =>
      `Long context costs more than people expect: each token of cache is ${f.kvKiB} KiB, so the full ${n(f.p.maxContext)} tokens add ${formatGiB(f.max.kvGiB)} GiB, about three and a half times the Q4_K_M weights. Fine-tunes and merges keep this exact shape, so their numbers match this page.`,
    related: 'DeepSeek-R1-Distill-Llama 8B shares this architecture byte for byte; Qwen2.5 7B is the closest alternative with a much smaller cache.',
    faqs: (f) => [
      {
        q: 'Can Llama 3.1 8B run on an 8 GB GPU?',
        a: `Yes at Q4_K_M: ${g(f.q4)} at 8,192 tokens of context. At 16,384 tokens it rises to ${g(f.at('q4_k_m', 16384))} and no longer fits, and Q8_0 at ${g(f.q8)} needs ${tier(f.q8)}.`,
      },
      {
        q: 'How much VRAM does Llama 3.1 8B need at 128k context?',
        a: `${g(f.max)} at Q4_K_M, because the KV cache grows to ${formatGiB(f.max.kvGiB)} GiB at ${n(f.p.maxContext)} tokens. That needs ${tier(f.max)}, unless the runtime quantizes the cache.`,
      },
      {
        q: 'Is FP16 worth it for Llama 3.1 8B?',
        a: `Rarely for inference. FP16 needs ${g(f.fp16)} against ${g(f.q8)} for Q8_0, and Q8_0's output is practically indistinguishable. FP16 matters for fine-tuning, which needs far more memory than this estimate anyway.`,
      },
    ],
  },
  'llama-3-1-70b': {
    about:
      'Llama 3.1 70B is Meta\'s mid-size flagship from July 2024, the model people move to when an 8B answer is not good enough and a hosted API is not an option.',
    pick: (f) =>
      `Q4_K_M at ${g(f.q4)} is the realistic target and fits ${tier(f.q4)} or two 24 GiB cards split across layers. Q8_0 at ${g(f.q8)} needs ${tier(f.q8)}. Q3_K_M at ${g(f.at('q3_k_m'))} is the floor before quality falls off noticeably.`,
    pitfall: (f) =>
      `FP16 at ${g(f.fp16)} does not fit any single card in the tier list, and splitting across GPUs adds a little overhead per device that this estimate does not model. On Apple Silicon, remember the GPU gets about three quarters of unified memory by default, so a 64 GB Mac has roughly 48 GB usable, which is tight for Q4_K_M.`,
    related: 'DeepSeek-R1-Distill-Llama 70B uses the same shape; Qwen2.5 72B is the nearest rival at a similar size.',
    faqs: (f) => [
      {
        q: 'Can Llama 3.1 70B run on two RTX 3090s?',
        a: `At Q4_K_M, yes: the estimate is ${g(f.q4)} at 8,192 tokens, under the 48 GiB the pair provides. At 32,768 tokens it climbs to ${g(f.at('q4_k_m', 32768))} and no longer fits.`,
      },
      {
        q: 'How much VRAM does Llama 3.1 70B need at FP16?',
        a: `${g(f.fp16)} at 8,192 tokens, of which ${formatGiB(f.fp16.weightsGiB)} GiB is weights. That is more than a single 80 GiB A100 or H100, so FP16 means at least two of them.`,
      },
    ],
  },
  'llama-3-1-405b': {
    about:
      'Llama 3.1 405B is the largest dense open-weight model Meta released in July 2024; it is a datacentre model, and running it locally is a multi-GPU or very-large-Mac project.',
    pick: (f) =>
      `Even Q4_K_M needs ${g(f.q4)}, so every quantization here exceeds a single 80 GiB card. Q8_0 at ${g(f.q8)} is a cluster job, and FP16 at ${g(f.fp16)} is what Meta's own FP8 release was made to avoid. Q4_K_M across four 80 GiB GPUs, or Q3_K_M at ${g(f.at('q3_k_m'))}, are the practical routes.`,
    pitfall: (f) =>
      `The KV cache is the small part here: ${formatGiB(f.q4.kvGiB)} GiB at 8,192 tokens and ${formatGiB(f.max.kvGiB)} GiB at ${n(f.p.maxContext)}, thanks to only ${f.p.kvHeads} KV heads. Splitting across GPUs adds per-device buffers this estimate does not include, and across machines the network becomes the bottleneck, not memory.`,
    related: 'For most local work Llama 3.1 70B or Qwen2.5 72B get much of the quality at a fraction of the memory.',
    faqs: (f) => [
      {
        q: 'How many GPUs does Llama 3.1 405B need?',
        a: `At Q4_K_M the estimate is ${g(f.q4)}, so three 80 GiB cards on paper and four in practice once per-GPU buffers are counted; at Q8_0 it is ${g(f.q8)}, six or more. FP16 at ${g(f.fp16)} needs ten 80 GiB cards before any per-GPU overhead.`,
      },
      {
        q: 'Can Llama 3.1 405B run on a Mac?',
        a: `Only on the largest unified-memory configurations. Q4_K_M needs ${g(f.q4)}, and macOS lets the GPU use only part of unified memory by default (the limit can be raised with the \`iogpu.wired_limit_mb\` sysctl), so a 256 GB machine is too small and a 512 GB one is the realistic minimum.`,
      },
    ],
  },
  'qwen2-5-7b': {
    about:
      'Qwen2.5 7B, from Alibaba\'s September 2024 release, is a strong general and multilingual 7B with unusually good maths and coding for its size.',
    pick: (f) =>
      `Q4_K_M at ${g(f.q4)} leaves headroom on an 8 GiB card; Q8_0 at ${g(f.q8)} needs ${tier(f.q8)} and is the quality pick; FP16 at ${g(f.fp16)} needs ${tier(f.fp16)}.`,
    pitfall: (f) =>
      `This model has only ${f.p.kvHeads} KV heads, so its cache costs ${f.kvKiB} KiB per token, less than half of Llama 3.1 8B's. The base config allows ${n(f.p.maxContext)} tokens, but the instruct model ships configured for 32,768; Qwen documents YaRN rope scaling for longer inputs, which some runtimes apply statically and which can slightly hurt short prompts.`,
    related: 'DeepSeek-R1-Distill-Qwen 7B has the identical shape; Llama 3.1 8B and Mistral 7B v0.3 are the usual comparisons.',
    faqs: (f) => [
      {
        q: 'Can Qwen2.5 7B run on a 6 GB GPU?',
        a: `At Q4_K_M with 8,192 tokens the estimate is ${g(f.q4)}, just inside 6 GiB with little to spare. Q3_K_M at ${g(f.at('q3_k_m'))} gives more headroom at some quality cost.`,
      },
      {
        q: 'How much VRAM does Qwen2.5 7B need for 32k context?',
        a: `${g(f.at('q4_k_m', 32768))} at Q4_K_M, of which ${formatGiB(f.at('q4_k_m', 32768).kvGiB)} GiB is KV cache, so it still fits ${tier(f.at('q4_k_m', 32768))}.`,
      },
    ],
  },
  'qwen2-5-14b': {
    about:
      'Qwen2.5 14B sits in the gap between 7B-class models and 32B ones, and is a common pick for a 12 or 16 GiB card that should do more than chat.',
    pick: (f) =>
      `Q4_K_M at ${g(f.q4)} fits ${tier(f.q4)}. Q5_K_M at ${g(f.at('q5_k_m'))} is a good middle step on 16 GiB, and Q8_0 at ${g(f.q8)} needs ${tier(f.q8)}.`,
    pitfall: (f) =>
      `With ${f.p.layers} layers its cache costs ${f.kvKiB} KiB per token, so context eats a 12 GiB card fast: 16,384 tokens at Q4_K_M already need ${g(f.at('q4_k_m', 16384))}. As with all Qwen2.5 instruct models, contexts past 32,768 tokens rely on YaRN rope scaling.`,
    related: 'DeepSeek-R1-Distill-Qwen 14B is this architecture with reasoning training; Mistral Nemo 12B is a smaller alternative.',
    faqs: (f) => [
      {
        q: 'Can Qwen2.5 14B run on a 12 GB GPU?',
        a: `Yes at Q4_K_M with up to 8,192 tokens: ${g(f.q4)}. At 16,384 tokens it needs ${g(f.at('q4_k_m', 16384))}, which calls for ${tier(f.at('q4_k_m', 16384))}.`,
      },
      {
        q: 'What is the best quantization for Qwen2.5 14B on a 16 GB card?',
        a: `Q5_K_M at ${g(f.at('q5_k_m'))} with 8,192 tokens, or Q4_K_M if you want 32,768 tokens of context (${g(f.at('q4_k_m', 32768))}). Q8_0 at ${g(f.q8)} does not fit 16 GiB.`,
      },
    ],
  },
  'qwen2-5-32b': {
    about:
      'Qwen2.5 32B is the largest Qwen2.5 model that fits a single 24 GiB consumer card when quantized, which makes it a favourite for one-GPU workstations.',
    pick: (f) =>
      `Q4_K_M at ${g(f.q4)} is the 24 GiB answer. Q5_K_M at ${g(f.at('q5_k_m'))} just misses 24 GiB and needs ${tier(f.at('q5_k_m'))}; Q8_0 at ${g(f.q8)} needs ${tier(f.q8)}.`,
    pitfall: (f) =>
      `On a 24 GiB card the margin is thin: 16,384 tokens at Q4_K_M come to ${g(f.at('q4_k_m', 16384))}, and the desktop compositor or a browser using the same GPU can tip it over. Contexts past 32,768 tokens need YaRN rope scaling.`,
    related: 'DeepSeek-R1-Distill-Qwen 32B shares the shape; Gemma 2 27B is the other 24 GiB-class choice.',
    faqs: (f) => [
      {
        q: 'Can Qwen2.5 32B run on an RTX 4090?',
        a: `Yes at Q4_K_M: ${g(f.q4)} at 8,192 tokens and ${g(f.at('q4_k_m', 16384))} at 16,384, both under 24 GiB. At 32,768 tokens it needs ${g(f.at('q4_k_m', 32768))}.`,
      },
      {
        q: 'How much VRAM does Qwen2.5 32B need at Q8_0?',
        a: `${g(f.q8)} at 8,192 tokens, so ${tier(f.q8)} or two 24 GiB cards.`,
      },
    ],
  },
  'qwen2-5-72b': {
    about:
      'Qwen2.5 72B is the top of Alibaba\'s open Qwen2.5 line and competes with Llama 3.1 70B, with particular strength in maths, code and non-English text.',
    pick: (f) =>
      `Q4_K_M at ${g(f.q4)} fits ${tier(f.q4)} or a pair of 24 GiB cards. Q5_K_M at ${g(f.at('q5_k_m'))} overflows 48 GiB, and Q8_0 at ${g(f.q8)} needs ${tier(f.q8)}.`,
    pitfall: (f) =>
      `Its weights are about ${formatGiB(f.q4.weightsGiB - estimate({ params: 70, quant: 'q4_k_m', context: f.ctx, preset: 'llama-3-1-70b' }).weightsGiB)} GiB larger than Llama 3.1 70B's at Q4_K_M, which matters when a 48 GiB setup is already full. Native context is 32,768 tokens; longer inputs need YaRN scaling.`,
    related: 'Compare Llama 3.1 70B and DeepSeek-R1-Distill-Llama 70B at the same tier, or step down to Qwen2.5 32B.',
    faqs: (f) => [
      {
        q: 'Can Qwen2.5 72B run on 48 GB of VRAM?',
        a: `At Q4_K_M with 8,192 tokens, yes: ${g(f.q4)}. At 16,384 tokens the estimate is ${g(f.at('q4_k_m', 16384))}, very close to the limit, and 32,768 tokens need ${g(f.at('q4_k_m', 32768))}.`,
      },
      {
        q: 'How much VRAM does Qwen2.5 72B need at FP16?',
        a: `${g(f.fp16)} at 8,192 tokens, more than any single 80 GiB card, so FP16 means two or more datacentre GPUs.`,
      },
    ],
  },
  'mistral-7b-v0-3': {
    about:
      'Mistral 7B v0.3, released in May 2024, extended the vocabulary to 32,768 tokens and added function calling; it remains a light, Apache-2.0 7B for chat and agents.',
    pick: (f) =>
      `Q4_K_M at ${g(f.q4)} fits an 8 GiB card with room for a longer context; Q8_0 at ${g(f.q8)} needs ${tier(f.q8)}, and FP16 at ${g(f.fp16)} needs ${tier(f.fp16)}.`,
    pitfall: (f) =>
      `Its maximum context is ${n(f.p.maxContext)} tokens, a quarter of the Llama 3.1 and Qwen2.5 models, and at that length the cache is ${formatGiB(f.max.kvGiB)} GiB. Unlike v0.1, v0.3 does not use sliding-window attention, so the full cache really is allocated.`,
    related: 'Mistral Nemo 12B is the bigger, 128k-context sibling; Llama 3.1 8B and Qwen2.5 7B are the same-size alternatives.',
    faqs: (f) => [
      {
        q: 'Can Mistral 7B v0.3 run on an 8 GB GPU at its full 32k context?',
        a: `Not at Q4_K_M: ${g(f.max)} at ${n(f.p.maxContext)} tokens needs ${tier(f.max)}. At 16,384 tokens it is ${g(f.at('q4_k_m', 16384))}, which fits.`,
      },
      {
        q: 'How much VRAM does Mistral 7B need at Q8_0?',
        a: `${g(f.q8)} at 8,192 tokens, so ${tier(f.q8)}.`,
      },
    ],
  },
  'mistral-nemo-12b': {
    about:
      'Mistral Nemo 12B, built by Mistral AI with NVIDIA and released in July 2024 under Apache 2.0, offers a 128k context and the Tekken tokenizer at a size that suits 12 and 16 GiB cards.',
    pick: (f) =>
      `Q4_K_M at ${g(f.q4)} fits ${tier(f.q4)}; Q5_K_M at ${g(f.at('q5_k_m'))} still fits 12 GiB, and Q8_0 at ${g(f.q8)} needs ${tier(f.q8)}.`,
    pitfall: (f) =>
      `Its head dimension is ${f.p.headDim}, set explicitly in the config rather than derived from the hidden size, which is why calculators that divide hidden size by heads overestimate its cache. The full ${n(f.p.maxContext)} tokens add ${formatGiB(f.max.kvGiB)} GiB of cache. Mistral recommends a lower sampling temperature than most models, around 0.3.`,
    related: 'Compare Mistral 7B v0.3 for less memory, or Qwen2.5 14B and Gemma 2 9B at a similar tier.',
    faqs: (f) => [
      {
        q: 'Can Mistral Nemo 12B run on a 12 GB GPU?',
        a: `Yes at Q4_K_M: ${g(f.q4)} at 8,192 tokens and ${g(f.at('q4_k_m', 16384))} at 16,384. At 32,768 tokens it needs ${g(f.at('q4_k_m', 32768))}, which calls for ${tier(f.at('q4_k_m', 32768))}.`,
      },
      {
        q: 'How much VRAM does Mistral Nemo need for its full 128k context?',
        a: `${g(f.max)} at Q4_K_M, with ${formatGiB(f.max.kvGiB)} GiB of KV cache, so ${tier(f.max)}.`,
      },
    ],
  },
  'gemma-2-9b': {
    about:
      'Gemma 2 9B, released by Google in June 2024, punches above its size on chat benchmarks; Gemma 3 has since superseded it, but it remains common in local setups as of October 2026.',
    pick: (f) =>
      `Q4_K_M at ${g(f.q4)} needs ${tier(f.q4)}, slightly more than other 7-9B models; Q8_0 at ${g(f.q8)} needs ${tier(f.q8)}, and FP16 at ${g(f.fp16)} needs ${tier(f.fp16)}.`,
    pitfall: (f) =>
      `Gemma 2 is capped at ${n(f.p.maxContext)} tokens, so the default context on this page is already the maximum. Its head dimension of ${f.p.headDim} makes the cache unusually heavy at ${f.kvKiB} KiB per token. Half its layers use a 4,096-token sliding window; this estimate allocates a full cache for every layer, so runtimes that exploit the window need less.`,
    related: 'Gemma 2 27B is the bigger sibling; Llama 3.1 8B and Qwen2.5 7B fit a smaller card at the same context.',
    faqs: (f) => [
      {
        q: 'Can Gemma 2 9B run on an 8 GB GPU?',
        a: `At its full 8,192 tokens the Q4_K_M estimate is ${g(f.q4)}, over 8 GiB, mostly because the cache is ${formatGiB(f.q4.kvGiB)} GiB. At 4,096 tokens it drops to ${g(f.at('q4_k_m', 4096))} and fits.`,
      },
      {
        q: 'Why does Gemma 2 9B need more VRAM than Llama 3.1 8B?',
        a: `Its cache costs ${f.kvKiB} KiB per token against 128 KiB for Llama 3.1 8B, because it has 42 layers and a head dimension of 256. At 8,192 tokens that is ${formatGiB(f.q4.kvGiB)} GiB of cache.`,
      },
    ],
  },
  'gemma-2-27b': {
    about:
      'Gemma 2 27B, Google\'s largest Gemma 2 model from June 2024, was built to run inference at full precision on a single 80 GB datacentre GPU such as an A100 or H100; quantized, it fits a single 24 GiB consumer card.',
    pick: (f) =>
      `Q4_K_M at ${g(f.q4)} fits ${tier(f.q4)}; Q8_0 at ${g(f.q8)} needs ${tier(f.q8)}, and FP16 at ${g(f.fp16)} needs ${tier(f.fp16)}.`,
    pitfall: (f) =>
      `Like the 9B, it stops at ${n(f.p.maxContext)} tokens, and ${f.p.kvHeads} KV heads make the cache ${f.kvKiB} KiB per token, ${formatGiB(f.q4.kvGiB)} GiB at the cap. Half the layers use a 4,096-token sliding window, so runtimes that exploit it allocate less than this estimate.`,
    related: 'Qwen2.5 32B and DeepSeek-R1-Distill-Qwen 32B compete for the same 24 GiB card; Gemma 2 9B is the small sibling.',
    faqs: (f) => [
      {
        q: 'Can Gemma 2 27B run on an RTX 4090?',
        a: `Yes at Q4_K_M: ${g(f.q4)} at its full 8,192-token context. Q5_K_M at ${g(f.at('q5_k_m'))} also fits 24 GiB; Q8_0 at ${g(f.q8)} does not.`,
      },
      {
        q: 'Can Gemma 2 27B use more than 8k context?',
        a: `No. Its configuration sets ${n(f.p.maxContext)} as the maximum position, and pushing past it without a long-context fine-tune degrades output. Gemma 3 is the Google option for longer contexts.`,
      },
    ],
  },
  'mixtral-8x7b': {
    about:
      'Mixtral 8x7B, released by Mistral AI in December 2023, is a sparse mixture-of-experts model: eight experts per layer, two active for each token, about 12.9B parameters doing work out of 46.7B in total.',
    pick: (f) =>
      `Q4_K_M at ${g(f.q4)} needs ${tier(f.q4)}; Q3_K_M at ${g(f.at('q3_k_m'))} narrowly misses a 24 GiB card at 8,192 tokens. Q8_0 at ${g(f.q8)} needs ${tier(f.q8)}.`,
    pitfall: (f) =>
      `The trap is sizing by active parameters. Every expert has to be resident, so memory follows the 46.7B total, while speed follows the 12.9B active. That is why it runs like a 13B but needs memory like a 47B. Partial offload of experts to system RAM works better than with dense models. Context tops out at ${n(f.p.maxContext)} tokens, ${formatGiB(f.max.kvGiB)} GiB of cache.`,
    related: 'Mistral 7B v0.3 shares its attention shape; Qwen2.5 32B and Gemma 2 27B are dense models in the same memory class.',
    faqs: (f) => [
      {
        q: 'How much VRAM does Mixtral 8x7B need?',
        a: `About ${g(f.q4)} at Q4_K_M with 8,192 tokens, ${g(f.q8)} at Q8_0 and ${g(f.fp16)} at FP16. All 46.7B parameters count, not the 12.9B active per token.`,
      },
      {
        q: 'Can Mixtral 8x7B run on a 24 GB GPU?',
        a: `Not entirely in VRAM at Q4_K_M (${g(f.q4)}). Q3_K_M with 4,096 tokens comes to ${g(f.at('q3_k_m', 4096))}, which fits; otherwise offload some experts to system RAM and accept slower generation.`,
      },
    ],
  },
  'deepseek-r1-distill-qwen-7b': {
    short: 'DeepSeek R1 Qwen 7B',
    about: `DeepSeek-R1-Distill-Qwen 7B was released in January 2025 alongside DeepSeek-R1, fine-tuned from Qwen2.5-Math-7B to reason step by step, and is strongest at maths. ${R1_NOTE}`,
    pick: (f) =>
      `Q4_K_M at ${g(f.q4)} fits an 8 GiB card; Q8_0 at ${g(f.q8)} needs ${tier(f.q8)}. Because answers depend on long, exact reasoning chains, Q5_K_M or better is worth it when memory allows.`,
    pitfall: (f) =>
      `${R1_THINK} With only ${f.p.kvHeads} KV heads this model's cache is cheap, ${f.kvKiB} KiB per token, so 32,768 tokens at Q4_K_M still come to ${g(f.at('q4_k_m', 32768))}. DeepSeek recommends a temperature around 0.6 and no system prompt.`,
    related: 'Qwen2.5 7B is the same architecture; DeepSeek-R1-Distill-Qwen 14B and DeepSeek-R1-Distill-Llama 8B are the neighbouring distills.',
    faqs: (f) => [
      {
        q: 'Can DeepSeek-R1 7B run on an 8 GB GPU?',
        a: `Yes. Q4_K_M needs ${g(f.q4)} at 8,192 tokens and ${g(f.at('q4_k_m', 32768))} at 32,768 tokens, enough for long reasoning traces. Q8_0 at ${g(f.q8)} needs ${tier(f.q8)}.`,
      },
      {
        q: 'Is DeepSeek-R1 7B the same as DeepSeek-R1?',
        a: 'No. It is Qwen2.5-Math-7B fine-tuned on reasoning data generated by DeepSeek-R1. The full R1 is a 671B mixture-of-experts model that needs hundreds of GiB even quantized.',
      },
    ],
  },
  'deepseek-r1-distill-qwen-14b': {
    short: 'DeepSeek R1 Qwen 14B',
    about: `DeepSeek-R1-Distill-Qwen 14B, from January 2025, is fine-tuned from Qwen2.5-14B and is often called the sweet spot of the distills for a single mid-range GPU. ${R1_NOTE}`,
    pick: (f) =>
      `Q4_K_M at ${g(f.q4)} fits ${tier(f.q4)}; Q5_K_M at ${g(f.at('q5_k_m'))} wants 16 GiB, and Q8_0 at ${g(f.q8)} needs ${tier(f.q8)}.`,
    pitfall: (f) =>
      `${R1_THINK} At ${f.kvKiB} KiB per token, a 32,768-token budget at Q4_K_M needs ${g(f.at('q4_k_m', 32768))}, which rules out a 12 GiB card for long problems.`,
    related: 'Qwen2.5 14B is the base architecture; DeepSeek-R1-Distill-Qwen 7B and 32B bracket it.',
    faqs: (f) => [
      {
        q: 'Can DeepSeek-R1 14B run on a 12 GB GPU?',
        a: `Yes at Q4_K_M with 8,192 tokens: ${g(f.q4)}. Long reasoning traces are the limit: 16,384 tokens need ${g(f.at('q4_k_m', 16384))}, beyond 12 GiB.`,
      },
      {
        q: 'How much VRAM does DeepSeek-R1 14B need at Q8_0?',
        a: `${g(f.q8)} at 8,192 tokens, so ${tier(f.q8)}.`,
      },
      {
        q: 'What context should I give DeepSeek-R1 14B on a 16 GB card?',
        a: `Q4_K_M with 32,768 tokens comes to ${g(f.at('q4_k_m', 32768))}, which fits 16 GiB and leaves room for long chains of thought.`,
      },
    ],
  },
  'deepseek-r1-distill-qwen-32b': {
    short: 'DeepSeek R1 Qwen 32B',
    about: `DeepSeek-R1-Distill-Qwen 32B, released in January 2025 and fine-tuned from Qwen2.5-32B, scored higher than the 70B distill on AIME 2024 in DeepSeek's own results. ${R1_NOTE}`,
    pick: (f) =>
      `Q4_K_M at ${g(f.q4)} fits ${tier(f.q4)}, the reason this distill is popular on single RTX 4090 and 3090 machines. Q8_0 at ${g(f.q8)} needs ${tier(f.q8)}.`,
    pitfall: (f) =>
      `${R1_THINK} On 24 GiB that is the squeeze: 16,384 tokens at Q4_K_M need ${g(f.at('q4_k_m', 16384))}, and 32,768 tokens need ${g(f.at('q4_k_m', 32768))}, which no longer fits.`,
    related: 'Qwen2.5 32B is the base architecture; DeepSeek-R1-Distill-Llama 70B is the next step up.',
    faqs: (f) => [
      {
        q: 'Can DeepSeek-R1 32B run on an RTX 4090?',
        a: `Yes at Q4_K_M up to about 16,384 tokens: ${g(f.q4)} at 8,192 and ${g(f.at('q4_k_m', 16384))} at 16,384. At 32,768 tokens it needs ${g(f.at('q4_k_m', 32768))}.`,
      },
      {
        q: 'Can DeepSeek-R1 32B run on 16 GB?',
        a: `Not fully in VRAM. Even Q3_K_M needs ${g(f.at('q3_k_m'))} at 8,192 tokens, so a 16 GiB card would have to offload layers to system RAM.`,
      },
    ],
  },
  'deepseek-r1-distill-llama-8b': {
    short: 'DeepSeek R1 Llama 8B',
    about: `DeepSeek-R1-Distill-Llama 8B, from January 2025, is Llama 3.1 8B fine-tuned to reason step by step. ${R1_NOTE}`,
    pick: (f) =>
      `Q4_K_M at ${g(f.q4)} fits an 8 GiB card at 8,192 tokens; Q8_0 at ${g(f.q8)} needs ${tier(f.q8)}.`,
    pitfall: (f) =>
      `${R1_THINK} This distill has twice the KV heads of the Qwen 7B distill, ${f.kvKiB} KiB per token, so 16,384 tokens at Q4_K_M already need ${g(f.at('q4_k_m', 16384))} and overflow 8 GiB.`,
    related: 'Llama 3.1 8B is the base architecture; DeepSeek-R1-Distill-Qwen 7B is the lighter-cache alternative.',
    faqs: (f) => [
      {
        q: 'Can DeepSeek-R1 Llama 8B run on an 8 GB GPU?',
        a: `At Q4_K_M with 8,192 tokens, yes: ${g(f.q4)}. For longer reasoning, 16,384 tokens need ${g(f.at('q4_k_m', 16384))}, so ${tier(f.at('q4_k_m', 16384))}.`,
      },
      {
        q: 'Which is lighter, DeepSeek-R1 Llama 8B or Qwen 7B?',
        a: `The Qwen 7B distill. At 8,192 tokens and Q4_K_M this one needs ${g(f.q4)}; the Qwen 7B distill has half the KV heads and smaller weights.`,
      },
    ],
  },
  'deepseek-r1-distill-llama-70b': {
    short: 'DeepSeek R1 Llama 70B',
    about: `DeepSeek-R1-Distill-Llama 70B, from January 2025, is the largest distill, fine-tuned from Llama-3.3-70B-Instruct, which shares Llama 3.1 70B's architecture. ${R1_NOTE}`,
    pick: (f) =>
      `Q4_K_M at ${g(f.q4)} fits ${tier(f.q4)} or two 24 GiB cards; Q8_0 at ${g(f.q8)} needs ${tier(f.q8)}.`,
    pitfall: (f) =>
      `${R1_THINK} At Q4_K_M, 16,384 tokens need ${g(f.at('q4_k_m', 16384))} and 32,768 need ${g(f.at('q4_k_m', 32768))}, past 48 GiB. On a Mac, the GPU's default share of unified memory is about three quarters, so 64 GB is tight and 96 GB comfortable.`,
    related: 'Llama 3.1 70B is the same shape; DeepSeek-R1-Distill-Qwen 32B is the single-24 GiB alternative.',
    faqs: (f) => [
      {
        q: 'Can DeepSeek-R1 70B run on two RTX 3090s?',
        a: `At Q4_K_M with up to about 16,384 tokens: ${g(f.q4)} at 8,192 and ${g(f.at('q4_k_m', 16384))} at 16,384, under 48 GiB. At 32,768 tokens it needs ${g(f.at('q4_k_m', 32768))}.`,
      },
      {
        q: 'How much VRAM does DeepSeek-R1 70B need at FP16?',
        a: `${g(f.fp16)} at 8,192 tokens, more than a single 80 GiB GPU.`,
      },
    ],
  },
};

function variant(p: ModelPreset): LlmVramVariant {
  const h = HAND[p.slug];
  if (!h) throw new Error(`llm-vram variant ${p.slug}: no hand-written copy`);
  const f = facts(p);
  const vram: VramInput = { params: p.params, quant: 'q4_k_m', context: f.ctx, preset: p.slug };
  const short = h.short ?? p.name;
  const longTitle = `${short} VRAM Requirements — Q4, Q8, FP16 + KV Cache`;
  const atMax = f.ctx === p.maxContext;

  return {
    slug: p.slug,
    input: [vram.params, vram.quant, vram.context, vram.preset].join('|'),
    vram,
    h1Name: `${p.name} VRAM`,
    headline: 'what it needs at Q4_K_M, Q8_0 and FP16',
    title: longTitle.length <= 60 ? longTitle : `${short} VRAM Requirements — Q4, Q8, FP16`,
    description: `${short} needs ${g(f.q4)} at Q4_K_M, ${g(f.q8)} at Q8_0 and ${g(f.fp16)} at FP16 with an 8k context. KV cache, GPU fit and quant advice.`,
    lede: `At Q4_K_M with an ${n(f.ctx)}-token context, ${p.name} needs about ${formatGiB(estimate(vram).totalGiB)} GiB of VRAM: ${formatGiB(f.q4.weightsGiB)} GiB of weights, ${formatGiB(f.q4.kvGiB)} GiB of KV cache and ${formatGiB(f.q4.overheadGiB)} GiB of runtime overhead. The smallest common GPU tier that holds it is ${tierWithCards(f.q4)}.`,
    sections: [
      {
        heading: `How much VRAM ${p.name} needs`,
        paragraphs: [
          h.about,
          `With ${n(f.ctx)} tokens of context the estimate is ${g(f.fp16)} at FP16, ${g(f.q8)} at Q8_0 and ${g(f.q4)} at Q4_K_M. FP16 needs ${tier(f.fp16)}, Q8_0 needs ${tier(f.q8)}, and Q4_K_M needs ${tier(f.q4)}. The weights are ${p.params} billion parameters times the bits per weight of each format (${f.fp16.bpw}, ${f.q8.bpw} and ${f.q4.bpw}), divided by eight; everything is in GiB, the unit GPU memory is sold in.`,
        ],
      },
      {
        heading: 'Context length and the KV cache',
        paragraphs: [
          `The KV cache stores a key and a value vector for every token in every layer. ${p.name} has ${p.layers} layers, ${p.kvHeads} KV heads and a head dimension of ${p.headDim}, read from its Hugging Face \`config.json\`, so at FP16 each token costs ${f.kvKiB} KiB. That is ${formatGiB(f.q4.kvGiB)} GiB at ${n(f.ctx)} tokens${
            atMax
              ? `, which is also the model's maximum context.`
              : `, and ${formatGiB(f.max.kvGiB)} GiB at the maximum of ${n(p.maxContext)}, where the Q4_K_M total becomes ${g(f.max)} and needs ${tier(f.max)}.`
          } The cache does not shrink with weight quantization; only a runtime option that quantizes the cache itself does.`,
        ],
      },
      { heading: 'Which quantization to pick', paragraphs: [h.pick(f)] },
      { heading: 'Pitfalls', paragraphs: [h.pitfall(f), h.related] },
    ],
    faqs: h.faqs(f),
  };
}

export const llmVramVariants: LlmVramVariant[] = PRESETS.map(variant);
